# Setup
title:               Holbloom
tagline:             'Consulting'
description:         'The Holbloom Consulting blog for programming and system internals'
url:                 https://blog.holbloom.com
baseurl:             ''
paginate:            10
# permalink:           pretty
permalink: /:categories/:title

# About/contact
author:
  name:              Holbloom Consulting
  url:               https://holbloom.com
  email:             contact@holbloom.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
